plugins:
  quizzing_alert_quizzes_left:
    default: 10
  quizzing_enabled:
    default: true
    client: true
  quizzing_show_who_quizd:
    default: true
    client: true
  quizzing_show_quizzes_on_profile:
    default: true
    client: true
  quizzing_tl0_quiz_limit:
    default: 2
  quizzing_tl1_quiz_limit:
    default: 4
  quizzing_tl2_quiz_limit:
    default: 6
  quizzing_tl3_quiz_limit:
    default: 8
  quizzing_tl4_quiz_limit:
    default: 10
